server:
  port: 8281

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: p1

server:
  port: 8281

---
spring:
  profiles: p2

server:
  port: 8282

---
spring:
  profiles: p3

server:
  port: 8283
